# deep learning settings
WEIGHT_DECAY: 0.0005
LEARNING_RATE: 10e-4
MOMENTUM: 0.99
DOWNSIZE_FILTER_FACTOR: 32
EPOCHS: 1
TOP_KERNEL_SIZE: 1
BOTTOM_KERNEL_SIZE: 1
BATCH_SIZE: 10

# file settings
RESULT_PATH: "results"
LOG_DIR: "logs/"

# experimental settings
SEED: 765687
CROSS_VALIDATION: 5
VALIDATION_PROP: 0.50

# augmentation settings
ROTATION_SETTINGS:
  ANGLE_MAX: 30
  ANGLE_TICKS: 1

CROP_TARGET: 300

# evualation settings
WRITE_IMAGES: True
WRITE_HISTOGRAM: True

DIST_THRESH: 3

# tensorboard settings
RESULT_STUDIES: 10
TB_IMAGES_COUNT: 1
TB_IMAGE_ITER: 1
IMAGES_AROUND_TRUE_SLICE: 3
